---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-compass
  labels:
    app: mongodb-compass
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30081
  selector:
    app: mongodb-compass
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-compass
  labels:
    app: mongodb-compass
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-compass
  template:
    metadata:
      labels:
        app: mongodb-compass
    spec:
      containers:
      - name: mongodb-compass
        image: mongo-express:1.0.0-alpha.4
        ports:
        - containerPort: 8081
        env:
        - name: ME_CONFIG_MONGODB_SERVER
          value: "mongodb"
        - name: ME_CONFIG_MONGODB_PORT
          value: "27017"
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: username
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: password
        - name: ME_CONFIG_BASICAUTH_USERNAME
          value: "admin"
        - name: ME_CONFIG_BASICAUTH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: compass-secret
              key: password
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Secret
metadata:
  name: compass-secret
type: Opaque
data:
  # Base64 encoded password for MongoDB Compass web UI access
  password: Y29tcGFzc3Bhc3N3b3Jk  # base64 encoded "compasspassword" 